apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: finmanage
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: finmanage-config
                  key: GF_SECURITY_ADMIN_PASSWORD
            - name: GF_USERS_ALLOW_SIGN_UP
              valueFrom:
                configMapKeyRef:
                  name: finmanage-config
                  key: GF_USERS_ALLOW_SIGN_UP
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboards-provider
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboards-json
              mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: grafana-datasources
          hostPath:
            path: /opt/suivi-depenses/grafana/provisioning/datasources
            type: Directory
        - name: grafana-dashboards-provider
          hostPath:
            path: /opt/suivi-depenses/grafana/provisioning/dashboards
            type: Directory
        - name: grafana-dashboards-json
          hostPath:
            path: /opt/suivi-depenses/grafana/dashboards
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: finmanage
spec:
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
      protocol: TCP
  selector:
    app: grafana
  type: NodePort
