# System Configuration
app_dir: "/opt/suivi-depenses"

# Docker Container Application Ports
mysql_port: "3306"
api_port: "8080"
interface_port: "80"

# Secret Credentials
# mysql_password is injected at runtime via GitHub Actions secrets (-e mysql_password=...)
